// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BHmsMAtT4Zs2wK2BTpyu1UWKNZqoG14',
    appId: '1:861608593316:web:fa8964d140025bb0e96331',
    messagingSenderId: '861608593316',
    projectId: 'plan-social-app',
    authDomain: 'plan-social-app.firebaseapp.com',
    storageBucket: 'plan-social-app.firebasestorage.app',
    measurementId: 'G-Y9Q5WB4REW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7XQgtzNCNy5lYdVP2phPsnmhswXMNSg',
    appId: '1:861608593316:android:0180b7738065e14fe96331',
    messagingSenderId: '861608593316',
    projectId: 'plan-social-app',
    storageBucket: 'plan-social-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3wBxlTtCE6NY4J0rEalB_98q-MpF-5vg',
    appId: '1:861608593316:ios:dda7395fc1337490e96331',
    messagingSenderId: '861608593316',
    projectId: 'plan-social-app',
    storageBucket: 'plan-social-app.firebasestorage.app',
    iosClientId: '861608593316-l1qqhkh3ruijck714c8j4qn7fgvpjckp.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3wBxlTtCE6NY4J0rEalB_98q-MpF-5vg',
    appId: '1:861608593316:ios:dda7395fc1337490e96331',
    messagingSenderId: '861608593316',
    projectId: 'plan-social-app',
    storageBucket: 'plan-social-app.firebasestorage.app',
    iosClientId: '861608593316-l1qqhkh3ruijck714c8j4qn7fgvpjckp.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-BHmsMAtT4Zs2wK2BTpyu1UWKNZqoG14',
    appId: '1:861608593316:web:ff8785aeede3f428e96331',
    messagingSenderId: '861608593316',
    projectId: 'plan-social-app',
    authDomain: 'plan-social-app.firebaseapp.com',
    storageBucket: 'plan-social-app.firebasestorage.app',
    measurementId: 'G-6HSG2CHZ79',
  );

}