name: dating_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  geolocator: ^10.0.3
  image_picker: ^0.8.7+5
  google_fonts: ^4.0.3
  file_picker: ^5.2.0
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.4
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  google_maps_webservice: ^0.0.20-nullsafety.5
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher_adaptative_fore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon.png
    - assets/boton-editar.png
    - assets/boton-union.png
    - assets/icono-ubicacion.png
