name: dating_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  geolocator: ^10.0.3
  image_picker: ^0.8.7+5
  google_fonts: ^4.0.3
  file_picker: ^9.0.2
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.4
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  shared_preferences: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  image_cropper: ^9.0.0
  http: ^1.3.0
  intl: ^0.19.0
  share_plus: ^10.1.4
  video_player: ^2.5.5
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.1.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/plan.png"

flutter:
  uses-material-design: true
  assets:
    #- assets/launcher_icon.png
    - assets/boton-editar.png
    - assets/icono-ubicacion.png
    - assets/plan.png
    - assets/plan-sin-fondo.png
    - assets/anadir.svg
    - assets/casa.svg
    - assets/corazon.png
    - assets/mensaje.svg
    - assets/union.svg
    - assets/usuario.svg
    - assets/lupa.svg
    - assets/notificacion.png
    - assets/filter.png
    - assets/menu.png
    - assets/agregar-usuario.svg
    - assets/users.svg
    - assets/sin-plan.svg
    - assets/anadir-imagen.svg
    - assets/corazon.svg
    - assets/compartir.svg
    - assets/icono-deporte.svg
    - assets/icono-cafe.svg
    - assets/icono-cena.svg
    - assets/icono-fiesta.svg
    - assets/icono-cine.svg
    - assets/icono-excursion.svg
    - assets/icono-tour-cultural.svg
    - assets/icono-yoga.svg
    - assets/icono-baile.svg
    - assets/icono-concierto-musica.svg
    - assets/icono-juegos.svg
    - assets/icono-sesion-estudio.svg
    - assets/icono-viaje.svg
    - assets/icono-charla-seminario.svg
    - assets/icono-calendario.svg
    - assets/icono-ubicacion.svg
    - assets/icono-ubicacion-interno.svg
    - assets/icono-max-participantes.svg
    - assets/icono-plan-publico.svg
    - assets/icono-plan-privado.svg
    - assets/icono-plan-seguidores.svg
    - assets/icono-id-plan.svg
    - assets/icono-descripcion-plan.svg
    - assets/icono-mapa.svg
    - assets/icono-globo-usuario.svg
    - assets/icono-ajustes.svg
    - assets/icono-centro-ayuda.svg
    - assets/icono-cerrar-sesion.svg
    - assets/icono-corazon.svg
    - assets/icono-seguidores.svg
    - assets/icono-usuario-basico.png
    - assets/icono-usuario-premium.png
    - assets/icono-usuario-golden.png
    - assets/icono-usuario-vip.png
    - assets/icono-tick.svg
    - assets/icono-fecha-creacion.svg
    - assets/icono-restriccion-edad.svg
    - assets/icono-compartir.svg
    - assets/icono-candado.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
