name: dating_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  geolocator: ^10.0.3
  image_picker: ^0.8.7+5
  google_fonts: ^4.0.3
  file_picker: ^5.2.0
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.4
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  shared_preferences: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.1.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/plan.png"

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon.png
    - assets/boton-editar.png
    - assets/icono-ubicacion.png
    - assets/plan.png
    - assets/plan-sin-fondo.png
    - assets/anadir.svg
    - assets/casa.svg
    - assets/corazon.png
    - assets/mensaje.svg
    - assets/union.png
    - assets/usuario.svg
    - assets/lupa.svg
    - assets/notificacion.png
    - assets/filter.png
    - assets/menu.png
    - assets/agregar-usuario.svg


  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
